### ISSUE TITLE
Cant find config file 

### ISSUE THREAD

**Issue by maxsptz** [loics2/sorta#10]
Hello, im trying to find my config file, but even when searching my whole pc, it seems like i can find it. Maybe im searching for the wrong file name? Thanks!

**Comment by maxsptz** [comment]
Fixed it myself! Its a hidden file so you need to make it show. I did this on mac by pressing 
"CMD + Shift + ."

**Comment by loics2** [comment]
Yep, on Unix systems, files and folders with a `.` as a first character in their name is hidden.
