### ISSUE TITLE
Improve doc strings, update docs to Sphinx

### ISSUE THREAD

**Issue by talaniz** [loics2/sorta#6]
I really like your library, it's a great idea and it has some great features you could implement. While I was working on some tests for this library, I noticed that some of the doc strings could use some improvement. For example, this function `cli` has a doc string that seems like it would fit more in the README file--

```
@click.group()
def cli():
    """Sorta is a tool helping you to sort your files."""
```

Doc strings should explain what the function or class does or why you chose to make a design decision. Please reach out if you'd like to work on this with me and I can ask you some questions about what some of these functions do so we can improve them. 
    I also have some experience generating documentation from Sphinx, so I'd be happy to transition them over to this library and generate some html based docs as well.

**Comment by loics2** [comment]
Thanks! Yeah I admit that I'm not the best at documenting things... I never heard of Sphinx, but it looks cool. So feel free to make the documentation better!

About this `cli` function, it's used as an entry point for `click`, and isn't really used for anything else, that's why it has a shitty docstring...

**Comment by talaniz** [comment]
Thanks for getting back to me. I'll run through some of the doc strings and see what can be improved. If I'm unsure of what a particular function does, I'll just post here to ask you. I think the `cli` function docstring could probably just be what you told me "An entry point for click". Will send over another pull request.
